[package]
name = "edot_editor"
version.workspace = true
edition.workspace = true

[dependencies]
bevy.workspace = true
bevy_egui.workspace = true
edot_tab.workspace = true
edot_inspector.workspace = true
transform-gizmo-bevy.workspace = true