[package]
name = "edot_inspector"
version.workspace = true
edition.workspace = true

[dependencies]
bevy.workspace = true
bevy_egui.workspace = true
itoa.workspace = true

[[example]]
name = "inspect_entity_component"
path = "examples/entity_component.rs"